// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: alarm.proto

package alarm;

public final class AlarmServiceImpl {
  private AlarmServiceImpl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_alarm_Point_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_alarm_Point_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_alarm_RouteNote_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_alarm_RouteNote_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\013alarm.proto\022\005alarm\",\n\005Point\022\020\n\010latitud" +
      "e\030\001 \001(\001\022\021\n\tlongitude\030\002 \001(\001\"8\n\tRouteNote\022" +
      "\036\n\010location\030\001 \001(\0132\014.alarm.Point\022\013\n\003tag\030\002" +
      " \001(\t2C\n\014AlarmService\0223\n\rrouteTracking\022\014." +
      "alarm.Point\032\020.alarm.RouteNote(\0010\001B\033\n\005ala" +
      "rmB\020AlarmServiceImplP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_alarm_Point_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_alarm_Point_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_alarm_Point_descriptor,
        new java.lang.String[] { "Latitude", "Longitude", });
    internal_static_alarm_RouteNote_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_alarm_RouteNote_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_alarm_RouteNote_descriptor,
        new java.lang.String[] { "Location", "Tag", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
