// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: alarm.proto

package alarm;

public final class AlarmServiceImpl {
  private AlarmServiceImpl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_alarm_Point_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_alarm_Point_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_alarm_Livestock_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_alarm_Livestock_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_alarm_Route_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_alarm_Route_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\013alarm.proto\022\005alarm\",\n\005Point\022\020\n\010latitud" +
      "e\030\001 \001(\005\022\021\n\tlongitude\030\002 \001(\005\":\n\tLivestock\022" +
      "\r\n\005tagId\030\001 \001(\005\022\036\n\010location\030\002 \001(\0132\014.alarm" +
      ".Point\"8\n\005Route\022\036\n\010location\030\001 \001(\0132\014.alar" +
      "m.Point\022\017\n\007message\030\002 \001(\t2l\n\014AlarmService" +
      "\022+\n\tGetAnimal\022\014.alarm.Point\032\020.alarm.Live" +
      "stock\022/\n\rRouteTracking\022\014.alarm.Route\032\014.a" +
      "larm.Route(\0010\001B\033\n\005alarmB\020AlarmServiceImp" +
      "lP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_alarm_Point_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_alarm_Point_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_alarm_Point_descriptor,
        new java.lang.String[] { "Latitude", "Longitude", });
    internal_static_alarm_Livestock_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_alarm_Livestock_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_alarm_Livestock_descriptor,
        new java.lang.String[] { "TagId", "Location", });
    internal_static_alarm_Route_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_alarm_Route_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_alarm_Route_descriptor,
        new java.lang.String[] { "Location", "Message", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
