// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: alarm.proto

package alarm;

public interface LivestockOrBuilder extends
    // @@protoc_insertion_point(interface_extends:alarm.Livestock)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * The id of the animal.
   * </pre>
   *
   * <code>int32 tagId = 1;</code>
   */
  int getTagId();

  /**
   * <pre>
   * The point where the animal is detected.
   * </pre>
   *
   * <code>.alarm.Point location = 2;</code>
   */
  boolean hasLocation();
  /**
   * <pre>
   * The point where the animal is detected.
   * </pre>
   *
   * <code>.alarm.Point location = 2;</code>
   */
  alarm.Point getLocation();
  /**
   * <pre>
   * The point where the animal is detected.
   * </pre>
   *
   * <code>.alarm.Point location = 2;</code>
   */
  alarm.PointOrBuilder getLocationOrBuilder();
}
