// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: alarm.proto

package alarm;

/**
 * Protobuf type {@code alarm.Livestock}
 */
public  final class Livestock extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:alarm.Livestock)
    LivestockOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Livestock.newBuilder() to construct.
  private Livestock(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Livestock() {
    tagId_ = 0;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private Livestock(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            tagId_ = input.readInt32();
            break;
          }
          case 18: {
            alarm.Point.Builder subBuilder = null;
            if (location_ != null) {
              subBuilder = location_.toBuilder();
            }
            location_ = input.readMessage(alarm.Point.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(location_);
              location_ = subBuilder.buildPartial();
            }

            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return alarm.AlarmServiceImpl.internal_static_alarm_Livestock_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return alarm.AlarmServiceImpl.internal_static_alarm_Livestock_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            alarm.Livestock.class, alarm.Livestock.Builder.class);
  }

  public static final int TAGID_FIELD_NUMBER = 1;
  private int tagId_;
  /**
   * <pre>
   * The id of the animal.
   * </pre>
   *
   * <code>int32 tagId = 1;</code>
   */
  public int getTagId() {
    return tagId_;
  }

  public static final int LOCATION_FIELD_NUMBER = 2;
  private alarm.Point location_;
  /**
   * <pre>
   * The point where the animal is detected.
   * </pre>
   *
   * <code>.alarm.Point location = 2;</code>
   */
  public boolean hasLocation() {
    return location_ != null;
  }
  /**
   * <pre>
   * The point where the animal is detected.
   * </pre>
   *
   * <code>.alarm.Point location = 2;</code>
   */
  public alarm.Point getLocation() {
    return location_ == null ? alarm.Point.getDefaultInstance() : location_;
  }
  /**
   * <pre>
   * The point where the animal is detected.
   * </pre>
   *
   * <code>.alarm.Point location = 2;</code>
   */
  public alarm.PointOrBuilder getLocationOrBuilder() {
    return getLocation();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (tagId_ != 0) {
      output.writeInt32(1, tagId_);
    }
    if (location_ != null) {
      output.writeMessage(2, getLocation());
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (tagId_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, tagId_);
    }
    if (location_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getLocation());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof alarm.Livestock)) {
      return super.equals(obj);
    }
    alarm.Livestock other = (alarm.Livestock) obj;

    boolean result = true;
    result = result && (getTagId()
        == other.getTagId());
    result = result && (hasLocation() == other.hasLocation());
    if (hasLocation()) {
      result = result && getLocation()
          .equals(other.getLocation());
    }
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + TAGID_FIELD_NUMBER;
    hash = (53 * hash) + getTagId();
    if (hasLocation()) {
      hash = (37 * hash) + LOCATION_FIELD_NUMBER;
      hash = (53 * hash) + getLocation().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static alarm.Livestock parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static alarm.Livestock parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static alarm.Livestock parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static alarm.Livestock parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static alarm.Livestock parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static alarm.Livestock parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static alarm.Livestock parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static alarm.Livestock parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static alarm.Livestock parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static alarm.Livestock parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static alarm.Livestock parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static alarm.Livestock parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(alarm.Livestock prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code alarm.Livestock}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:alarm.Livestock)
      alarm.LivestockOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return alarm.AlarmServiceImpl.internal_static_alarm_Livestock_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return alarm.AlarmServiceImpl.internal_static_alarm_Livestock_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              alarm.Livestock.class, alarm.Livestock.Builder.class);
    }

    // Construct using alarm.Livestock.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      tagId_ = 0;

      if (locationBuilder_ == null) {
        location_ = null;
      } else {
        location_ = null;
        locationBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return alarm.AlarmServiceImpl.internal_static_alarm_Livestock_descriptor;
    }

    @java.lang.Override
    public alarm.Livestock getDefaultInstanceForType() {
      return alarm.Livestock.getDefaultInstance();
    }

    @java.lang.Override
    public alarm.Livestock build() {
      alarm.Livestock result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public alarm.Livestock buildPartial() {
      alarm.Livestock result = new alarm.Livestock(this);
      result.tagId_ = tagId_;
      if (locationBuilder_ == null) {
        result.location_ = location_;
      } else {
        result.location_ = locationBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof alarm.Livestock) {
        return mergeFrom((alarm.Livestock)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(alarm.Livestock other) {
      if (other == alarm.Livestock.getDefaultInstance()) return this;
      if (other.getTagId() != 0) {
        setTagId(other.getTagId());
      }
      if (other.hasLocation()) {
        mergeLocation(other.getLocation());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      alarm.Livestock parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (alarm.Livestock) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private int tagId_ ;
    /**
     * <pre>
     * The id of the animal.
     * </pre>
     *
     * <code>int32 tagId = 1;</code>
     */
    public int getTagId() {
      return tagId_;
    }
    /**
     * <pre>
     * The id of the animal.
     * </pre>
     *
     * <code>int32 tagId = 1;</code>
     */
    public Builder setTagId(int value) {
      
      tagId_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The id of the animal.
     * </pre>
     *
     * <code>int32 tagId = 1;</code>
     */
    public Builder clearTagId() {
      
      tagId_ = 0;
      onChanged();
      return this;
    }

    private alarm.Point location_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        alarm.Point, alarm.Point.Builder, alarm.PointOrBuilder> locationBuilder_;
    /**
     * <pre>
     * The point where the animal is detected.
     * </pre>
     *
     * <code>.alarm.Point location = 2;</code>
     */
    public boolean hasLocation() {
      return locationBuilder_ != null || location_ != null;
    }
    /**
     * <pre>
     * The point where the animal is detected.
     * </pre>
     *
     * <code>.alarm.Point location = 2;</code>
     */
    public alarm.Point getLocation() {
      if (locationBuilder_ == null) {
        return location_ == null ? alarm.Point.getDefaultInstance() : location_;
      } else {
        return locationBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * The point where the animal is detected.
     * </pre>
     *
     * <code>.alarm.Point location = 2;</code>
     */
    public Builder setLocation(alarm.Point value) {
      if (locationBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        location_ = value;
        onChanged();
      } else {
        locationBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <pre>
     * The point where the animal is detected.
     * </pre>
     *
     * <code>.alarm.Point location = 2;</code>
     */
    public Builder setLocation(
        alarm.Point.Builder builderForValue) {
      if (locationBuilder_ == null) {
        location_ = builderForValue.build();
        onChanged();
      } else {
        locationBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <pre>
     * The point where the animal is detected.
     * </pre>
     *
     * <code>.alarm.Point location = 2;</code>
     */
    public Builder mergeLocation(alarm.Point value) {
      if (locationBuilder_ == null) {
        if (location_ != null) {
          location_ =
            alarm.Point.newBuilder(location_).mergeFrom(value).buildPartial();
        } else {
          location_ = value;
        }
        onChanged();
      } else {
        locationBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <pre>
     * The point where the animal is detected.
     * </pre>
     *
     * <code>.alarm.Point location = 2;</code>
     */
    public Builder clearLocation() {
      if (locationBuilder_ == null) {
        location_ = null;
        onChanged();
      } else {
        location_ = null;
        locationBuilder_ = null;
      }

      return this;
    }
    /**
     * <pre>
     * The point where the animal is detected.
     * </pre>
     *
     * <code>.alarm.Point location = 2;</code>
     */
    public alarm.Point.Builder getLocationBuilder() {
      
      onChanged();
      return getLocationFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * The point where the animal is detected.
     * </pre>
     *
     * <code>.alarm.Point location = 2;</code>
     */
    public alarm.PointOrBuilder getLocationOrBuilder() {
      if (locationBuilder_ != null) {
        return locationBuilder_.getMessageOrBuilder();
      } else {
        return location_ == null ?
            alarm.Point.getDefaultInstance() : location_;
      }
    }
    /**
     * <pre>
     * The point where the animal is detected.
     * </pre>
     *
     * <code>.alarm.Point location = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        alarm.Point, alarm.Point.Builder, alarm.PointOrBuilder> 
        getLocationFieldBuilder() {
      if (locationBuilder_ == null) {
        locationBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            alarm.Point, alarm.Point.Builder, alarm.PointOrBuilder>(
                getLocation(),
                getParentForChildren(),
                isClean());
        location_ = null;
      }
      return locationBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:alarm.Livestock)
  }

  // @@protoc_insertion_point(class_scope:alarm.Livestock)
  private static final alarm.Livestock DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new alarm.Livestock();
  }

  public static alarm.Livestock getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Livestock>
      PARSER = new com.google.protobuf.AbstractParser<Livestock>() {
    @java.lang.Override
    public Livestock parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new Livestock(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<Livestock> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Livestock> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public alarm.Livestock getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

