// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: alarm.proto

package alarm;

public interface RouteNoteOrBuilder extends
    // @@protoc_insertion_point(interface_extends:alarm.RouteNote)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * The location from which the message is sent.
   * </pre>
   *
   * <code>.alarm.Point location = 1;</code>
   */
  boolean hasLocation();
  /**
   * <pre>
   * The location from which the message is sent.
   * </pre>
   *
   * <code>.alarm.Point location = 1;</code>
   */
  alarm.Point getLocation();
  /**
   * <pre>
   * The location from which the message is sent.
   * </pre>
   *
   * <code>.alarm.Point location = 1;</code>
   */
  alarm.PointOrBuilder getLocationOrBuilder();

  /**
   * <pre>
   * The message to be sent.
   * </pre>
   *
   * <code>string tag = 2;</code>
   */
  java.lang.String getTag();
  /**
   * <pre>
   * The message to be sent.
   * </pre>
   *
   * <code>string tag = 2;</code>
   */
  com.google.protobuf.ByteString
      getTagBytes();
}
