// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: lighting.proto

package lighting;

public interface PowerResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:lighting.PowerResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool switch = 1;</code>
   */
  boolean getSwitch();
}
