// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: livestock.proto

package livestock;

public final class LivestockServiceImpl {
  private LivestockServiceImpl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_livestock_LivestockRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_livestock_LivestockRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_livestock_LivestockResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_livestock_LivestockResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017livestock.proto\022\tlivestock\"\037\n\020Livestoc" +
      "kRequest\022\013\n\003tag\030\001 \001(\t\"\211\001\n\021LivestockRespo" +
      "nse\022\013\n\003tag\030\001 \001(\t\022\016\n\006gender\030\002 \001(\t\022\013\n\003dob\030" +
      "\003 \001(\t\022\023\n\013temperature\030\004 \001(\t\022\020\n\010feedTime\030\005" +
      " \001(\t\022\020\n\010latitude\030\006 \001(\005\022\021\n\tlongitude\030\007 \001(" +
      "\0052\\\n\020LivestockService\022H\n\tlivestock\022\033.liv" +
      "estock.LivestockRequest\032\034.livestock.Live" +
      "stockResponse0\001B#\n\tlivestockB\024LivestockS" +
      "erviceImplP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_livestock_LivestockRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_livestock_LivestockRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_livestock_LivestockRequest_descriptor,
        new java.lang.String[] { "Tag", });
    internal_static_livestock_LivestockResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_livestock_LivestockResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_livestock_LivestockResponse_descriptor,
        new java.lang.String[] { "Tag", "Gender", "Dob", "Temperature", "FeedTime", "Latitude", "Longitude", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
