// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: livestock.proto

package livestock;

public interface LivestockRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:livestock.LivestockRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string tag = 1;</code>
   */
  java.lang.String getTag();
  /**
   * <code>string tag = 1;</code>
   */
  com.google.protobuf.ByteString
      getTagBytes();
}
