// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: livestock.proto

package livestock;

public interface LivestockResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:livestock.LivestockResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string tag = 1;</code>
   */
  java.lang.String getTag();
  /**
   * <code>string tag = 1;</code>
   */
  com.google.protobuf.ByteString
      getTagBytes();

  /**
   * <code>string gender = 2;</code>
   */
  java.lang.String getGender();
  /**
   * <code>string gender = 2;</code>
   */
  com.google.protobuf.ByteString
      getGenderBytes();

  /**
   * <code>string dob = 3;</code>
   */
  java.lang.String getDob();
  /**
   * <code>string dob = 3;</code>
   */
  com.google.protobuf.ByteString
      getDobBytes();

  /**
   * <code>string temperature = 4;</code>
   */
  java.lang.String getTemperature();
  /**
   * <code>string temperature = 4;</code>
   */
  com.google.protobuf.ByteString
      getTemperatureBytes();

  /**
   * <code>string feedTime = 5;</code>
   */
  java.lang.String getFeedTime();
  /**
   * <code>string feedTime = 5;</code>
   */
  com.google.protobuf.ByteString
      getFeedTimeBytes();

  /**
   * <code>double latitude = 6;</code>
   */
  double getLatitude();

  /**
   * <code>double longitude = 7;</code>
   */
  double getLongitude();
}
