# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tractor.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='tractor.proto',
  package='tractor',
  syntax='proto3',
  serialized_options=b'\n\007tractorB\022TractorServiceImplP\001',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\rtractor.proto\x12\x07tractor\"\x1e\n\x0eTractorRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\"\"\n\x0fTractorResponse\x12\x0f\n\x07message\x18\x01 \x01(\t2U\n\x0eTractorService\x12\x43\n\x0eTractorDetails\x12\x17.tractor.TractorRequest\x1a\x18.tractor.TractorResponseB\x1f\n\x07tractorB\x12TractorServiceImplP\x01\x62\x06proto3'
)




_TRACTORREQUEST = _descriptor.Descriptor(
  name='TractorRequest',
  full_name='tractor.TractorRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='tractor.TractorRequest.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=26,
  serialized_end=56,
)


_TRACTORRESPONSE = _descriptor.Descriptor(
  name='TractorResponse',
  full_name='tractor.TractorResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='message', full_name='tractor.TractorResponse.message', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=58,
  serialized_end=92,
)

DESCRIPTOR.message_types_by_name['TractorRequest'] = _TRACTORREQUEST
DESCRIPTOR.message_types_by_name['TractorResponse'] = _TRACTORRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

TractorRequest = _reflection.GeneratedProtocolMessageType('TractorRequest', (_message.Message,), {
  'DESCRIPTOR' : _TRACTORREQUEST,
  '__module__' : 'tractor_pb2'
  # @@protoc_insertion_point(class_scope:tractor.TractorRequest)
  })
_sym_db.RegisterMessage(TractorRequest)

TractorResponse = _reflection.GeneratedProtocolMessageType('TractorResponse', (_message.Message,), {
  'DESCRIPTOR' : _TRACTORRESPONSE,
  '__module__' : 'tractor_pb2'
  # @@protoc_insertion_point(class_scope:tractor.TractorResponse)
  })
_sym_db.RegisterMessage(TractorResponse)


DESCRIPTOR._options = None

_TRACTORSERVICE = _descriptor.ServiceDescriptor(
  name='TractorService',
  full_name='tractor.TractorService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=94,
  serialized_end=179,
  methods=[
  _descriptor.MethodDescriptor(
    name='TractorDetails',
    full_name='tractor.TractorService.TractorDetails',
    index=0,
    containing_service=None,
    input_type=_TRACTORREQUEST,
    output_type=_TRACTORRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_TRACTORSERVICE)

DESCRIPTOR.services_by_name['TractorService'] = _TRACTORSERVICE

# @@protoc_insertion_point(module_scope)
