// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: lighting.proto

package lighting;

public interface LightResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:lighting.LightResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 light = 1;</code>
   */
  int getLight();
}
