// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: tractor.proto

package tractor;

public final class TractorServiceImpl {
  private TractorServiceImpl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tractor_TractorRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tractor_TractorRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tractor_TractorResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tractor_TractorResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rtractor.proto\022\007tractor\"\036\n\016TractorReque" +
      "st\022\014\n\004name\030\001 \001(\t\"\"\n\017TractorResponse\022\017\n\007m" +
      "essage\030\001 \001(\t2U\n\016TractorService\022C\n\016Tracto" +
      "rDetails\022\027.tractor.TractorRequest\032\030.trac" +
      "tor.TractorResponseB\037\n\007tractorB\022TractorS" +
      "erviceImplP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_tractor_TractorRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_tractor_TractorRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tractor_TractorRequest_descriptor,
        new java.lang.String[] { "Name", });
    internal_static_tractor_TractorResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_tractor_TractorResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tractor_TractorResponse_descriptor,
        new java.lang.String[] { "Message", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
